run:
  concurrency: 4
  deadline: 1m
  issues-exit-code: 1
  tests: true
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
linters:
  enable-all: false
  disable-all: false
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - exhaustive
    - exportloopref
    - gci
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goimports
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - nestif
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - testpackage
    - unconvert
    - unparam
    - whitespace
    - wsl
linters-settings:
  gocyclo:
    min-complexity: 15
issues:
  exclude-use-default: false
  max-per-linter: 1024
  max-same: 1024